Fix test failure due to unresolved template
Fixes e.g.
  File "test/easyconfigs/easyconfigs.py", line 1047, in test_r_libs_site_env_var
  if 'R_LIBS' in ec['ec'][key]:
  ...
easybuild.tools.build_log.EasyBuildError: 'Failed to resolve all templates in "/path/to/AlphaFold_DBs/%(versions)s" using template dictionary

Similar for other changes